### ISSUE TITLE
scc from snap package cannot open files

### ISSUE THREAD

**Issue by carlosame** [felicianotech/snap-scc#12]
I installed `scc` via snap on Xubuntu 19.04 and does not work. It always gives the same error:

`ERROR 2019-10-05T18:31:51Z: failed to open .: open .: permission denied`

or

`ERROR 2019-10-05T18:36:07Z: failed to open somedir: open somedir: permission denied`

However, when running from a local golang installation instead of the snap, `scc` works fine.

It is the latest snap, version:

```
$ scc --version
scc version 2.8.0
```

I mentioned the issue here: https://github.com/boyter/scc/issues/110

**Comment by FelicianoTech** [comment]
Can you please provide the output of both `pwd` and `ls -lah` from the directory that you were trying to use `scc` from?

**Comment by carlosame** [comment]
Here is the output that you asked for:
```
/var/tmp/tokei$ ls -lah
total 40K
drwxrwxr-x  9 carlos carlos 4,0K oct  5 20:45 .
drwxrwxrwt 14 root   root   4,0K oct  9 13:58 ..
drwxrwxr-x  5 carlos carlos 4,0K oct  5 00:32 carteci
-rwxr-xr-x  1 carlos carlos  632 oct  5 00:30 count
drwxrwxr-x  5 carlos carlos 4,0K oct  5 00:32 css4j
drwxrwxr-x  5 carlos carlos 4,0K oct  5 00:32 css4j-agent
drwxrwxr-x  5 carlos carlos 4,0K oct  5 00:32 css4j-awt
drwxrwxr-x  2 carlos carlos 4,0K oct  5 00:32 css4j-dist
drwxrwxr-x  5 carlos carlos 4,0K oct  5 00:32 css4j-dom4j
drwxrwxr-x  4 carlos carlos 4,0K oct  5 00:32 css4j-mark
/var/tmp/tokei$ pwd
/var/tmp/tokei
```

**Comment by carlosame** [comment]
If you want a replica of the tree, you can reproduce a somewhat similar tree by downloading https://github.com/css4j/css4j-dist/archive/master.zip then extracting and executing `./tree.sh` (requires subversion), although hopefully you do not need that level of replication to reproduce the issue.

**Comment by FelicianoTech** [comment]
Awesome thank you for providing that.

So snaps are designed with security in mind. By default, they can't read anything outside of your HOME directory nor can they read hidden files in your home directory.

Could you try your test again but with source code located in a directory within your `$HOME` please?

**Comment by carlosame** [comment]
I reinstalled the snap with --classic and now it reads the directories; I obviously do not use snaps a lot.

Thanks,
Carlos

**Comment by FelicianoTech** [comment]
No worries. Snaps are a fairly new technology that we're all still learning. I'll open an Issue to add a note to the readme for future users.

**Comment by Zitrax** [comment]
I also hit this, quite confusing error message. But thanks for the pointer here.

**Comment by FelicianoTech** [comment]
@Zitrax Do you have a suggestion on how I can make it easier to understand? Perhaps by explaining it better in the readme? Something else?

**Comment by Zitrax** [comment]
I think the main problem was that it did not really give me any hint on the underlying reason, I didn't have any directories with write protection. Can it know that it is a snap installation such that it could simply say something about that, like: "Snap only has access to your home directory" or similar?

Also it would be better if it used the absolute path, instead of ".", since it might not be 100% clear what that is, depending on your current working directory and how you run it.

**Comment by carlosame** [comment]
> Perhaps by explaining it better in the readme?

Although this is snap's fault, mentioning it in the README would help. A lot of people try to avoid snaps (because of the bloat, and I also find them less likely to be audited as compared to a distro-supported `.deb` for example) and rarely use them, but one is supposed to have to recall the detail about the default restriction to the home directory (I later recalled that I've already faced that in the past).
