### ISSUE TITLE
Add a snap home directory note to readme

### ISSUE THREAD

**Issue by FelicianoTech** [felicianotech/snap-scc#13]
See context in #12.

**Comment by Midorina** [comment]
can you do this? I am getting `failed to open .: open .: permission denied` even though I installed it with the `-classic` option

**Comment by Midorina** [comment]
it only took 2 years but better late than never I guess :)

**Comment by FelicianoTech** [comment]
> felicianotech commented on Oct 9, 2019

Wow. It was almost literally 2 years. Thanks for the bump! 😁
