### ISSUE TITLE
Merge into github.com/boyter/scc?

### ISSUE THREAD

**Issue by boyter** [felicianotech/snap-scc#6]
Hi Ricardo,

I was literally about to go though the process of setting up a snap for scc, thought I would check and noticed you had already done so! Thanks so much!

Would you like to work with me to get this into the scc pipelines so that it could be published on any new version when released? If not I am happy to have some sort of hook here so that you can always have the latest version available for everyone.

Let me know your thoughts, and thanks so much for taking the effort to do this.

**Comment by FelicianoTech** [comment]
Hey,

I typically have this updated within 48 hours of a release. That being said, an updated process will be great, especially if it's first party. My only concern is that I've seen some people ask to take over a publishing channel such as this, get tired of it in 6 months, and then it falls to the wayside.

That being said, I'm not sure what setup you're planning to use but the `snap/snapcraft.yaml` file is in this repo and theoretically should be portable to build wherever you want. If you get that setup and it works, we need to go over to the Snapcraft Forum and get this Snapcraft Store name for `scc` transferred over to you.

**Comment by boyter** [comment]
I don't mind you maintaining it at all! All I really want is to ensure that updates are pushed out promptly. If you have any ideas for how this would work with you I am happy to do it on my side to ensure the updates keep coming though.

**Comment by cardil** [comment]
Separate repository that holds only a snapcraft YAML file is not ideal. Version and link must be manually updated with git commit. This should be automatic.

If it can be merged to [boyter/scc](github.com/boyter/scc), releases can be make automatic by configuring appropriate CI job to listen on tags.

This issue is related to my proposal https://github.com/boyter/scc/issues/110

**Comment by FelicianoTech** [comment]
I've listed how the transfer could go earlier in this thread. Otherwise, this will be maintained as is until I automate it sometime in the next few months.
